apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: observability

spec:
  selector:
    matchLabels:
      app: metricbeat

  template:
    metadata:
      labels:
        app: metricbeat

    spec:
      serviceAccountName: metricbeat
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:8.19.16

        args:
        - "-e"
        - "-c"
        - "/etc/metricbeat.yml"

        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          subPath: metricbeat.yml

        - name: proc
          mountPath: /hostfs/proc
          readOnly: true

        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true

        env:
        - name: HOST_PROC
          value: /hostfs/proc

        - name: HOST_SYS
          value: /hostfs/sys
       
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
      volumes:

      - name: config
        configMap:
          name: metricbeat-config

      - name: proc
        hostPath:
          path: /proc

      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
