apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: portfolio

data:
  SMTP_USER: "pixelmint.mail@gmail.com"
  FRONTEND_URL: "http://13.126.253.67/"
  SMTP_HOST: "smtp.gmail.com"
  PORT: "4518"
  DEV_EMAIL: "moinnaik98@gmail.com"
  DEFAULT_CLIENT_IMG_SRC: "/src/assets/default-client-profile.jpg"
  APM_URL: "http://10.0.2.160:8200"
  BACKEND_SERVICE_NAME: "portfolio-backend"
