apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: portfolio

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      nodeSelector:
        node-type: app

      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z mongodb 27017
              do
                echo "Waiting for MongoDB..."
                sleep 5
              done

      revisionHistoryLimit: 3
      
      containers:
        - name: backend
          image: moinnaik/portfolio-backend:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 4518

          envFrom:
            - secretRef:
                name: backend-secret

          startupProbe:
            httpGet:
              path: /health
              port: 4518
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 4518
            initialDelaySeconds: 15
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 4518
            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
