pipeline {
  agent any

  environment {
    AWS_REGION = 'ap-south-1'
    ECR_REPO = '918792379419.dkr.ecr.ap-south-1.amazonaws.com/portfolio-backend'
  }

  stages {

    stage('Build Image') {
      steps { 
        script {
          dir('app/backend') {
            sh 'docker build -t portfolio-backend:$BUILD_NUMBER .'
          }
        }
      }
    }

    stage('Login ECR') {
      steps {
        sh '''
        aws ecr get-login-password \
        --region $AWS_REGION \
        | docker login \
        --username AWS \
        --password-stdin \
        $ECR_REPO
        '''
      }
    }

    stage('Push Image') {
      steps {
        sh '''
        docker tag portfolio-backend:latest $ECR_REPO:$BUILD_NUMBER
        docker push $ECR_REPO:$BUILD_NUMBER
        '''
      }
    }

    stage('Deploy') {
      steps {
        sh '''
        kubectl set image deployment/backend \
        backend=$ECR_REPO:$BUILD_NUMBER \
        -n portfolio

        kubectl rollout status deployment/backend \
        -n portfolio
        '''
      }
    }
  }
}