pipeline {
agent any

```
environment {
    AWS_REGION = "ap-south-1"
    AWS_ACCOUNT_ID = "918792379419"
    ECR_REPO = "portfolio-backend"
    IMAGE_TAG = "${BUILD_NUMBER}"
    IMAGE_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${IMAGE_TAG}"
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
                url: 'https://github.com/MoinMN/production-grade-mern-k8s-devops-project.git'
        }
    }

    stage('Build Docker Image') {
        steps {
            sh '''
                docker build -t ${ECR_REPO}:${IMAGE_TAG} ./backend
            '''
        }
    }

    stage('Login To ECR') {
        steps {
            withCredentials([
                [$class: 'AmazonWebServicesCredentialsBinding',
                 credentialsId: 'aws-ecr']
            ]) {
                sh '''
                    aws ecr get-login-password \
                    --region ${AWS_REGION} | \
                    docker login \
                    --username AWS \
                    --password-stdin \
                    ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                '''
            }
        }
    }

    stage('Tag Image') {
        steps {
            sh '''
                docker tag \
                ${ECR_REPO}:${IMAGE_TAG} \
                ${IMAGE_URI}
            '''
        }
    }

    stage('Push Image To ECR') {
        steps {
            sh '''
                docker push ${IMAGE_URI}
            '''
        }
    }

    stage('Deploy To Kubernetes') {
        steps {

            withCredentials([
                file(credentialsId: 'kubeconfig',
                variable: 'KUBECONFIG_FILE')
            ]) {

                sh '''
                    export KUBECONFIG=$KUBECONFIG_FILE

                    kubectl set image deployment/backend \
                    backend=${IMAGE_URI} \
                    -n portfolio

                    kubectl rollout status deployment/backend \
                    -n portfolio --timeout=300s
                '''
            }
        }
    }

}

post {

    success {
        echo "Deployment Successful"
        echo "Image: ${IMAGE_URI}"
    }

    failure {
        echo "Deployment Failed"
    }

    always {
        sh 'docker image prune -f || true'
    }
}
```

}
